### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar pelicula por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar peliculas por un genero
GET http://localhost:1234/movies?genreName=adventure

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "La camerusa",
  "year": 1994,
  "directorId": "Roger Waters, Bob Dylan",
  "duration": 666,
  "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
  "genreName": [
    "Animation"
  ]
}

### Borrar una peli
DELETE http://localhost:1234/movies/828737b0-5bfd-4881-9152-6ec8a2e96f3f

### Actualizar la pelicula (una parte)
PATCH http://localhost:1234/movies/19269443-2c34-4a26-baa3-03150daaa579
Content-Type: application/json

{
  "year": 1999
}