### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar pelicula por id
GET http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

### Recuperar peliculas por un genero
GET http://localhost:1234/movies?genre=romance

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "La camerusa",
  "year": 1994,
  "director": "Roger Waters, Bob Dylan",
  "duration": 666,
  "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
  "genre": [
    "Animation"
  ]
}

### Borrar una peli
DELETE http://localhost:1234/movies/e248d226-a190-11ee-94fa-2cf05d78338f

### Actualizar la pelicula (una parte)
PATCH http://localhost:1234/movies/5c93b190-9a0b-11ee-a318-2cf05d78338f
Content-Type: application/json

{
  "year": 2011,
  "rate": 5
}