### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar pelicula por id
GET http://localhost:1234/movies/48a3cec4-9a6f-11ee-8fd0-d85ed3a4f313

### Recuperar peliculas por un genero
GET http://localhost:1234/movies?genre=romance

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "La camerusa",
  "year": 1994,
  "director": "Roger Waters, Bob Dylan",
  "duration": 666,
  "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
  "genre": [
    "Animation"
  ]
}

### Borrar una peli
DELETE http://localhost:1234/movies/828737b0-5bfd-4881-9152-6ec8a2e96f3f

### Actualizar la pelicula (una parte)
PATCH http://localhost:1234/movies/48a3cec4-9a6f-11ee-8fd0-d85ed3a4f313
Content-Type: application/json

{
  "year": 2011
}